apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-ranked-server-bot-data
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "echo-ranked-server-bot.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: law-general-bots
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.botStorage.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.botStorage.size }}
