// <auto-generated />
using System;
using EchoRankedServerBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EchoRankedServerBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260324001624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EchoRankedServerBot.Data.Entities.PlayerIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvrId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NakamaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("NakamaId");

                    b.ToTable("player_identities", (string)null);
                });

            modelBuilder.Entity("EchoRankedServerBot.Data.Entities.PlayerMatchStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer");

                    b.Property<int>("Catches")
                        .HasColumnType("integer");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text");

                    b.Property<string>("EvrId")
                        .HasColumnType("text");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("Interceptions")
                        .HasColumnType("integer");

                    b.Property<int>("LongBounceShots")
                        .HasColumnType("integer");

                    b.Property<bool>("Lose")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Mvp")
                        .HasColumnType("boolean");

                    b.Property<double>("MvpScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Passes")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<double>("PossessionTime")
                        .HasColumnType("double precision");

                    b.Property<int>("Saves")
                        .HasColumnType("integer");

                    b.Property<int>("ShortBounceShots")
                        .HasColumnType("integer");

                    b.Property<string>("ShotSpeeds")
                        .HasColumnType("text");

                    b.Property<int>("ShotsTaken")
                        .HasColumnType("integer");

                    b.Property<int>("Steals")
                        .HasColumnType("integer");

                    b.Property<int>("Stuns")
                        .HasColumnType("integer");

                    b.Property<int>("ThreePointShots")
                        .HasColumnType("integer");

                    b.Property<string>("ThrowDistances")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwoPointShots")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserIp")
                        .HasColumnType("text");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("MatchName");

                    b.HasIndex("Timestamp");

                    b.ToTable("player_match_stats", (string)null);
                });

            modelBuilder.Entity("EchoRankedServerBot.Data.Entities.WatchedPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("IpAddress");

                    b.ToTable("watched_players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
